"""Outbound HTML sanitization pipeline for composed email bodies.

Mirror of the inbound :mod:`api.services.email_html_pipeline`, but with a
**much stricter** allowlist. The inbound pipeline renders arbitrary
third-party newsletter HTML inside a sandboxed iframe; this one cleans the
HTML the user composes in the rich-text editor before it is persisted to a
draft and sent through Gmail / Outlook. The composer (TipTap with our
restricted schema) only emits a small set of tags — bold, italic,
underline, bullet/numbered lists, links and the reply/forward quote
``<blockquote>`` — so the allowlist is intentionally tight: anything
outside it (pasted styles, ``<img>``, ``<table>``, ``<script>``, document
wrappers) is removed, keeping the user's text.

All functions are pure — no DB, no auth, no network. ``sanitize_outbound_html``
is the single entry point. Fail-soft: any unexpected error returns the
input unchanged so the sanitizer never raises a domain error.
"""

from __future__ import annotations

import logging

import bleach
from bleach.css_sanitizer import CSSSanitizer

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Allowlists (deliberately stricter than the inbound pipeline)
# ---------------------------------------------------------------------------

# The exact tag set the rich-text composer can emit. ``b``/``strong`` and
# ``i``/``em`` are both kept because TipTap / paste normalisation may emit
# either form.
_ALLOWED_TAGS: list[str] = [
    "p", "br", "strong", "b", "em", "i", "u",
    "ul", "ol", "li", "a", "blockquote",
]

# ``a`` carries link attributes; ``blockquote`` carries the minimal inline
# style of the reply/forward quote (generated by
# ``core.email.helpers.build_quoted_body_html``). No other tag may carry
# ``style`` — pasted inline styles on paragraphs / spans are dropped.
_ALLOWED_ATTRIBUTES: dict[str, list[str]] = {
    "a": ["href", "title", "target", "rel"],
    "blockquote": ["style"],
}

# Only navigation protocols. No ``cid`` / ``data`` — inline images in the
# outgoing body are out of scope for this feature.
_ALLOWED_PROTOCOLS: list[str] = ["http", "https", "mailto"]

# CSS properties allowed inside the ``blockquote`` ``style``. Limited to the
# vocabulary ``build_quoted_body_html`` uses for the quote frame. Keep this
# in lockstep with ``_HTML_QUOTE_BLOCKQUOTE_STYLE`` in
# ``core.email.helpers``.
_ALLOWED_CSS_PROPERTIES: frozenset[str] = frozenset({
    "margin", "margin-left", "padding", "padding-left", "border-left", "color",
})

# Forced on every surviving ``<a>`` so links open safely in a new tab and
# do not leak the referrer or pass link equity.
_FORCED_LINK_REL = "noopener noreferrer nofollow"
_FORCED_LINK_TARGET = "_blank"


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------


def sanitize_outbound_html(html: str) -> str:
    """Clean composer HTML before persisting / sending. Fail-soft.

    Applies the strict allowlist via bleach with ``strip=True`` (disallowed
    tags are removed but their text content is kept). Document wrappers
    (``<html>`` / ``<head>`` / ``<body>`` / ``<meta>``) are not in the
    allowlist, so bleach strips the tags and keeps the body content — a
    Graph-wrapped HTML body that ever reaches this function collapses to a
    clean fragment. Inline ``style`` survives only on ``<blockquote>`` and
    only for the allowlisted CSS properties. Every ``<a>`` is hardened to
    ``target="_blank" rel="noopener noreferrer nofollow"``.

    On any unexpected failure the input is returned unchanged (the caller
    treats the result as best-effort; the editor already restricts the
    schema on the client side).
    """
    if not html or html.isspace():
        return html
    try:
        css_sanitizer = CSSSanitizer(
            allowed_css_properties=_ALLOWED_CSS_PROPERTIES,
            allowed_svg_properties=frozenset(),
        )
        cleaned = bleach.clean(
            html,
            tags=_ALLOWED_TAGS,
            attributes=_ALLOWED_ATTRIBUTES,
            protocols=_ALLOWED_PROTOCOLS,
            css_sanitizer=css_sanitizer,
            strip=True,
        )
        return _harden_links_in_html(cleaned)
    except Exception as exc:
        logger.warning(
            "sanitize_outbound_html failed (%s): %s — returning input unchanged",
            type(exc).__name__, exc,
        )
        return html


def _harden_links_in_html(html: str) -> str:
    """Force ``target="_blank"`` + ``rel`` on every ``<a>`` start tag.

    Runs after bleach has already filtered tags / attributes / protocols,
    so only allowlisted links remain. Re-runs bleach with a linkify-style
    attribute callback is heavier than a token-stream filter; instead we
    use bleach's own html5lib serialiser through a tiny ``Filter`` so the
    rewrite stays robust against attribute quoting / ordering. Fail-soft:
    on any error the already-sanitised ``html`` is returned unchanged
    (links simply keep bleach's defaults).
    """
    if "<a" not in html.lower():
        return html
    try:
        from bleach.html5lib_shim import (
            BleachHTMLParser,
            BleachHTMLSerializer,
            Filter,
        )

        class _LinkHardeningFilter(Filter):
            def __iter__(self):
                for token in Filter.__iter__(self):
                    if (
                        token.get("type") in ("StartTag", "EmptyTag")
                        and token.get("name") == "a"
                    ):
                        data = token.setdefault("data", {})
                        data[(None, "target")] = _FORCED_LINK_TARGET
                        data[(None, "rel")] = _FORCED_LINK_REL
                    yield token

        parser = BleachHTMLParser(
            tags=_ALLOWED_TAGS,
            strip=True,
            consume_entities=False,
            namespaceHTMLElements=False,
        )
        dom = parser.parseFragment(html)
        walker = bleach.html5lib_shim.getTreeWalker("etree")
        stream = _LinkHardeningFilter(source=walker(dom))
        serializer = BleachHTMLSerializer(
            quote_attr_values="always",
            omit_optional_tags=False,
            escape_lt_in_attrs=True,
            resolve_entities=False,
            sanitize=False,
            alphabetical_attributes=False,
        )
        return serializer.render(stream)
    except Exception as exc:
        logger.warning(
            "outbound link hardening failed (%s): %s — keeping bleach defaults",
            type(exc).__name__, exc,
        )
        return html
