"""Autenticacion OAuth de Outlook: flujo interactivo con PKCE, refresco silencioso y perfil."""

from __future__ import annotations

import base64
import hashlib
import json
import logging
import secrets
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime, timedelta, timezone
from typing import Any

from ..errors import (
    EmailExternalAPIError,
    EmailMissingAppCredentialsError,
    EmailMissingRefreshTokenError,
    EmailMissingTokenError,
    EmailRefreshFailedError,
)
from ..helpers import parse_expiry, unwrap_app_credentials, unwrap_user_tokens, wrap_account_tokens
from .transporte import GRAPH_BASE_URL

logger = logging.getLogger(__name__)


OUTLOOK_SCOPES = [
    "https://graph.microsoft.com/Mail.ReadWrite",
    "https://graph.microsoft.com/Mail.Send",
    "https://graph.microsoft.com/User.Read",
    "offline_access",
]


class OutlookAutenticacionMixin:
    """Metodos de autenticacion de :class:`~core.email.outlook_client.cliente.OutlookClient`."""

    def begin_interactive_auth(
        self,
        app_credentials: dict[str, Any] | None = None,
        redirect_uri: str | None = None,
    ) -> dict[str, Any]:
        """
        Build the Microsoft authorization URL (PKCE) for a user-driven flow.

        The backend runs headless (container), so no browser is opened and
        no local callback server is started: the caller forwards the URL to
        the end user's browser and Microsoft redirects to the configured
        ``redirect_uri`` (an HTTP endpoint of this API, registered in the
        Azure app registration). When *redirect_uri* is not given, the one
        declared in the app credentials JSON is used.
        """
        credentials_payload = unwrap_app_credentials(app_credentials)
        if not credentials_payload:
            raise EmailMissingAppCredentialsError()

        client_id = str(credentials_payload.get("client_id") or "").strip()
        client_secret = str(credentials_payload.get("client_secret") or "").strip()
        tenant = str(credentials_payload.get("tenant") or "common").strip()
        resolved_redirect = str(redirect_uri or credentials_payload.get("redirect_uri") or "").strip()
        scopes = self._resolve_scopes(credentials_payload)

        if not client_id or not client_secret or not resolved_redirect or not scopes:
            raise EmailMissingAppCredentialsError("Missing required app credentials.")

        # PKCE code verifier / challenge
        code_verifier = secrets.token_urlsafe(72)[:128]
        if len(code_verifier) < 43:
            code_verifier = f"{code_verifier}{'x' * (43 - len(code_verifier))}"
        code_challenge = (
            base64.urlsafe_b64encode(
                hashlib.sha256(code_verifier.encode("utf-8")).digest()
            )
            .rstrip(b"=")
            .decode("utf-8")
        )
        state = secrets.token_urlsafe(32)

        authorize_url = f"https://login.microsoftonline.com/{tenant}/oauth2/v2.0/authorize"
        auth_query = {
            "client_id": client_id,
            "response_type": "code",
            "redirect_uri": resolved_redirect,
            "response_mode": "query",
            "scope": " ".join(scopes),
            "state": state,
            "code_challenge": code_challenge,
            "code_challenge_method": "S256",
            "prompt": "select_account",
        }
        auth_url = f"{authorize_url}?{urllib.parse.urlencode(auth_query)}"

        return {
            "authorization_url": auth_url,
            "state": state,
            "flow_state": {
                "code_verifier": code_verifier,
                "redirect_uri": resolved_redirect,
                "tenant": tenant,
                "scopes": scopes,
            },
        }

    def complete_interactive_auth(
        self,
        app_credentials: dict[str, Any] | None = None,
        flow_state: dict[str, Any] | None = None,
        code: str | None = None,
    ) -> dict[str, Any]:
        """
        Exchange the authorization code captured by the redirect callback
        for Outlook tokens, reusing the PKCE verifier generated by
        ``begin_interactive_auth``.
        """
        credentials_payload = unwrap_app_credentials(app_credentials)
        if not credentials_payload:
            raise EmailMissingAppCredentialsError()

        auth_code = str(code or "").strip()
        if not auth_code:
            raise EmailExternalAPIError("Outlook OAuth completion is missing the authorization code.")

        state_payload = dict(flow_state or {})
        code_verifier = str(state_payload.get("code_verifier") or "").strip()
        resolved_redirect = str(state_payload.get("redirect_uri") or "").strip()
        if not code_verifier or not resolved_redirect:
            raise EmailExternalAPIError("Outlook OAuth completion is missing the in-progress flow state.")

        client_id = str(credentials_payload.get("client_id") or "").strip()
        client_secret = str(credentials_payload.get("client_secret") or "").strip()
        if not client_id or not client_secret:
            raise EmailMissingAppCredentialsError("Missing required app credentials.")

        tenant = str(state_payload.get("tenant") or credentials_payload.get("tenant") or "common").strip()
        raw_scopes = state_payload.get("scopes")
        scopes = (
            [str(s).strip() for s in raw_scopes if str(s).strip()]
            if isinstance(raw_scopes, (list, tuple))
            else []
        ) or self._resolve_scopes(credentials_payload)
        token_url = self._token_url(tenant)

        try:
            token_response = self._token_request(token_url, {
                "grant_type": "authorization_code",
                "client_id": client_id,
                "client_secret": client_secret,
                "code": auth_code,
                "redirect_uri": resolved_redirect,
                "code_verifier": code_verifier,
                "scope": " ".join(scopes),
            })
        except EmailExternalAPIError:
            raise
        except Exception as exc:
            raise EmailExternalAPIError(
                f"Outlook unexpected token exchange error ({type(exc).__name__}): {exc}"
            ) from exc

        access_token = token_response.get("access_token")
        if not access_token:
            raise EmailExternalAPIError("Outlook failed to obtain access token: token response missing access_token.")

        self._access_token = access_token
        email_address, _display_name = self._fetch_sender_profile()

        token_record = {
            "access_token": access_token,
            "refresh_token": token_response.get("refresh_token"),
            "expiry": self._compute_expiry(token_response.get("expires_in")),
            "scopes": scopes,
            "email_address": email_address or None,
        }
        return wrap_account_tokens(token_record)

    def authenticate_silent(
        self,
        app_credentials: dict[str, Any] | None = None,
        user_tokens: dict[str, Any] | None = None,
    ) -> dict[str, Any] | None:
        """
        Non-interactive authentication: reuse a valid access token or refresh it.
        Returns updated wrapped tokens when a refresh occurs, None otherwise.
        Microsoft may rotate the refresh token on every refresh, so both the
        access and refresh tokens are persisted whenever a refresh happens.
        """
        credentials_payload = unwrap_app_credentials(app_credentials)
        if not credentials_payload:
            raise EmailMissingAppCredentialsError()

        token_payload = unwrap_user_tokens(user_tokens)
        access_token = token_payload.get("access_token")
        if not access_token:
            raise EmailMissingTokenError()

        refresh_token = token_payload.get("refresh_token")
        expiry = parse_expiry(token_payload.get("expiry"))

        # Determine whether the current access token has expired.
        is_expired = False
        if expiry is not None:
            now_utc = datetime.now(timezone.utc).replace(tzinfo=None)
            is_expired = expiry <= now_utc

        if not is_expired:
            self._access_token = access_token
            return None

        if not refresh_token:
            raise EmailMissingRefreshTokenError()

        client_id = str(credentials_payload.get("client_id") or "").strip()
        client_secret = str(credentials_payload.get("client_secret") or "").strip()
        tenant = str(credentials_payload.get("tenant") or "common").strip()
        scopes = self._resolve_scopes(credentials_payload, token_payload)

        if not client_id or not client_secret:
            raise EmailMissingAppCredentialsError("Missing required app credentials.")

        token_url = self._token_url(tenant)

        try:
            token_response = self._token_request(token_url, {
                "grant_type": "refresh_token",
                "client_id": client_id,
                "client_secret": client_secret,
                "refresh_token": refresh_token,
                "scope": " ".join(scopes),
            })
        except EmailExternalAPIError as exc:
            raise EmailRefreshFailedError(f"Outlook failed to refresh access token: {exc}") from exc
        except Exception as exc:
            raise EmailRefreshFailedError(
                f"Outlook unexpected refresh token exchange error ({type(exc).__name__}): {exc}"
            ) from exc

        new_access_token = token_response.get("access_token")
        if not new_access_token:
            raise EmailRefreshFailedError("Outlook failed to refresh access token: response missing access_token.")

        # Microsoft may return a new refresh token (rotating tokens).
        new_refresh_token = token_response.get("refresh_token") or refresh_token

        self._access_token = new_access_token

        token_record = {
            "access_token": new_access_token,
            "refresh_token": new_refresh_token,
            "expiry": self._compute_expiry(token_response.get("expires_in")),
            "scopes": scopes,
        }
        return wrap_account_tokens(token_record)

    def _fetch_sender_profile(self) -> tuple[str, str]:
        """Best-effort fetch of the authenticated user's email and display name (cached).

        Tries three strategies in order:
        1. GET /me (requires User.Read scope)
        2. Decode JWT access token claims
        3. Read the ``from`` field of a recently sent message (Mail.ReadWrite)
        """
        if self._sender_email is not None:
            return self._sender_email, self._sender_name or ""

        email, name = "", ""

        # Try 1: Graph API /me endpoint (needs User.Read scope)
        try:
            response = self._graph_request(
                "GET", f"{GRAPH_BASE_URL}/me?$select=displayName,mail,userPrincipalName",
            )
            email = response.get("mail") or response.get("userPrincipalName") or ""
            name = response.get("displayName") or ""
        except Exception as exc:
            logger.debug("Outlook /me profile fetch failed: %s", exc)

        # Try 2: decode JWT access token claims
        if not email:
            email, name = self._parse_token_claims()

        # Try 3: read from a recently sent message (needs Mail.ReadWrite)
        if not email:
            try:
                response = self._graph_request(
                    "GET",
                    f"{GRAPH_BASE_URL}/me/mailFolders/sentitems/messages?$top=1&$select=from",
                )
                messages = response.get("value", [])
                if messages:
                    from_obj = messages[0].get("from") or {}
                    email_addr = from_obj.get("emailAddress") or {}
                    email = email_addr.get("address") or ""
                    name = email_addr.get("name") or ""
            except Exception as exc:
                logger.debug("Outlook sent message profile fetch failed: %s", exc)

        self._sender_email = email
        self._sender_name = name
        return self._sender_email, self._sender_name

    def _parse_token_claims(self) -> tuple[str, str]:
        """Extract (email, display_name) from the JWT access token claims."""
        if not self._access_token:
            return "", ""
        try:
            parts = self._access_token.split(".")
            if len(parts) != 3:
                return "", ""
            payload = parts[1]
            padding = 4 - len(payload) % 4
            if padding != 4:
                payload += "=" * padding
            claims = json.loads(base64.urlsafe_b64decode(payload))
            email = (
                claims.get("preferred_username")
                or claims.get("email")
                or claims.get("unique_name")
                or claims.get("upn")
                or ""
            )
            name = claims.get("name") or ""
            return email, name
        except Exception as exc:
            logger.debug("Outlook failed to parse JWT claims: %s", exc)
            return "", ""

    def _resolve_scopes(
        self,
        credentials_payload: dict[str, Any],
        token_payload: dict[str, Any] | None = None,
    ) -> list[str]:
        """Resolve scopes from credentials or token payload, with a default fallback."""
        scopes_raw = credentials_payload.get("scopes")
        if scopes_raw is None and token_payload is not None:
            scopes_raw = token_payload.get("scopes")
        if isinstance(scopes_raw, str):
            return [s for s in scopes_raw.replace(",", " ").split() if s]
        if isinstance(scopes_raw, (list, tuple, set)):
            return [str(s).strip() for s in scopes_raw if str(s).strip()]
        return list(OUTLOOK_SCOPES)

    @staticmethod
    def _token_url(tenant: str) -> str:
        return f"https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token"

    @staticmethod
    def _compute_expiry(expires_in_raw: Any) -> str | None:
        if expires_in_raw is None:
            return None
        try:
            expires_in = int(expires_in_raw)
            if expires_in < 0:
                expires_in = 0
            return (datetime.now(timezone.utc) + timedelta(seconds=expires_in)).isoformat()
        except (TypeError, ValueError):
            return None

    def _token_request(self, token_url: str, payload: dict[str, str]) -> dict[str, Any]:
        """POST to the Microsoft identity token endpoint and return the parsed response."""
        data = urllib.parse.urlencode(payload).encode("utf-8")
        headers = {"Content-Type": "application/x-www-form-urlencoded"}
        req = urllib.request.Request(token_url, data=data, headers=headers, method="POST")

        try:
            with urllib.request.urlopen(req, timeout=30) as response:
                body = response.read().decode("utf-8")
        except urllib.error.HTTPError as exc:
            error_body = exc.read().decode("utf-8", errors="replace")
            detail = error_body
            try:
                error_json = json.loads(error_body) if error_body else {}
                if isinstance(error_json, dict):
                    err = error_json.get("error")
                    desc = error_json.get("error_description")
                    if err or desc:
                        detail = f"{err or 'error'}: {desc or 'unknown error'}"
            except (json.JSONDecodeError, TypeError, ValueError):
                pass
            raise EmailExternalAPIError(f"Outlook failed to call token endpoint: {detail}") from exc
        except urllib.error.URLError as exc:
            raise EmailExternalAPIError(f"Outlook failed to reach token endpoint: {exc.reason}") from exc
        except Exception as exc:
            raise EmailExternalAPIError(
                f"Outlook failed during token request ({type(exc).__name__}): {exc}"
            ) from exc

        try:
            token_response = json.loads(body) if body else {}
        except json.JSONDecodeError as exc:
            raise EmailExternalAPIError("Outlook failed to parse token endpoint response: invalid JSON.") from exc
        except Exception as exc:
            raise EmailExternalAPIError(
                f"Outlook failed during token response parsing ({type(exc).__name__}): {exc}"
            ) from exc

        if not isinstance(token_response, dict):
            raise EmailExternalAPIError("Outlook failed at token endpoint: invalid response payload.")

        if token_response.get("error"):
            err = str(token_response.get("error") or "error")
            desc = str(token_response.get("error_description") or "unknown error")
            raise EmailExternalAPIError(f"Outlook failed at token endpoint: {err}: {desc}")

        return token_response
