"""
Core email package public surface.
"""

from core.email.blocked_extensions import BLOCKED_EXTENSIONS, is_blocked_extension
from core.email.email_client import (
    AttachmentBinary,
    AttachmentMetadata,
    AttachmentUploadResult,
    DraftAttachmentInput,
    DraftMetadata,
    EmailClient,
    EmailContent,
    EmailMetadata,
    LabelUpdate,
    SpamMoveResult,
    SyncResult,
)
from core.email.email_manager import EmailManager
from core.email.errors import (
    CoreError,
    EmailAccountNotFoundError,
    EmailAccountRecordError,
    EmailAttachmentBlockedByProvider,
    EmailAttachmentDownloadFailed,
    EmailAttachmentNotFound,
    EmailAttachmentSendFailed,
    EmailAttachmentTooLargeForProvider,
    EmailAuthError,
    EmailConfigError,
    EmailDuplicateAccountLabelError,
    EmailError,
    EmailExternalAPIError,
    EmailInvalidCredentialsDataError,
    EmailInvalidExpiryError,
    EmailInvalidTokenDataError,
    EmailMissingAppCredentialsError,
    EmailMissingRefreshTokenError,
    EmailMissingTokenError,
    EmailNotAuthenticatedError,
    EmailProviderConfigError,
    EmailRecipientsMissingError,
    EmailRefreshFailedError,
)

__all__ = [
    "AttachmentBinary",
    "AttachmentMetadata",
    "AttachmentUploadResult",
    "BLOCKED_EXTENSIONS",
    "CoreError",
    "DraftAttachmentInput",
    "DraftMetadata",
    "EmailAccountNotFoundError",
    "EmailAccountRecordError",
    "EmailAttachmentBlockedByProvider",
    "EmailAttachmentDownloadFailed",
    "EmailAttachmentNotFound",
    "EmailAttachmentSendFailed",
    "EmailAttachmentTooLargeForProvider",
    "EmailAuthError",
    "EmailClient",
    "EmailContent",
    "EmailConfigError",
    "EmailDuplicateAccountLabelError",
    "EmailError",
    "EmailExternalAPIError",
    "EmailInvalidCredentialsDataError",
    "EmailInvalidExpiryError",
    "EmailInvalidTokenDataError",
    "EmailManager",
    "EmailMetadata",
    "LabelUpdate",
    "SpamMoveResult",
    "EmailMissingAppCredentialsError",
    "EmailMissingRefreshTokenError",
    "EmailMissingTokenError",
    "EmailNotAuthenticatedError",
    "EmailProviderConfigError",
    "EmailRecipientsMissingError",
    "EmailRefreshFailedError",
    "SyncResult",
    "is_blocked_extension",
]
