"""
Core email package public surface.
"""

from __future__ import annotations

from core.email.blocked_extensions import BLOCKED_EXTENSIONS, is_blocked_extension
from core.email.email_client import (
    AttachmentBinary,
    AttachmentMetadata,
    AttachmentUploadResult,
    DraftAttachmentInput,
    DraftMetadata,
    EmailClient,
    EmailContent,
    EmailMetadata,
    LabelUpdate,
    ReplyContext,
    SpamMoveResult,
    SyncResult,
)
from core.email.email_manager import EmailManager
from core.email.errors import (
    CoreError,
    EmailAccountNotFoundError,
    EmailAccountRecordError,
    EmailAttachmentBlockedByProvider,
    EmailAttachmentDownloadFailed,
    EmailAttachmentNotFound,
    EmailAttachmentSendFailed,
    EmailAttachmentTooLargeForProvider,
    EmailAuthError,
    EmailConfigError,
    EmailDuplicateAccountLabelError,
    EmailError,
    EmailExternalAPIError,
    EmailInvalidCredentialsDataError,
    EmailInvalidExpiryError,
    EmailInvalidTokenDataError,
    EmailMissingAppCredentialsError,
    EmailMissingRefreshTokenError,
    EmailMissingTokenError,
    EmailNotAuthenticatedError,
    EmailProviderConfigError,
    EmailRecipientsMissingError,
    EmailRefreshFailedError,
    EmailReplyContextFetchError,
)
from core.email.helpers import (
    build_in_reply_to_and_references,
    build_quoted_body,
    build_reply_subject,
    compute_reply_recipients,
    format_content_disposition,
    sanitize_filename,
    validate_reply_threading_coherence,
)

__all__ = [
    "AttachmentBinary",
    "AttachmentMetadata",
    "AttachmentUploadResult",
    "BLOCKED_EXTENSIONS",
    "CoreError",
    "DraftAttachmentInput",
    "DraftMetadata",
    "EmailAccountNotFoundError",
    "EmailAccountRecordError",
    "EmailAttachmentBlockedByProvider",
    "EmailAttachmentDownloadFailed",
    "EmailAttachmentNotFound",
    "EmailAttachmentSendFailed",
    "EmailAttachmentTooLargeForProvider",
    "EmailAuthError",
    "EmailClient",
    "EmailContent",
    "EmailConfigError",
    "EmailDuplicateAccountLabelError",
    "EmailError",
    "EmailExternalAPIError",
    "EmailInvalidCredentialsDataError",
    "EmailInvalidExpiryError",
    "EmailInvalidTokenDataError",
    "EmailManager",
    "EmailMetadata",
    "LabelUpdate",
    "SpamMoveResult",
    "EmailMissingAppCredentialsError",
    "EmailMissingRefreshTokenError",
    "EmailMissingTokenError",
    "EmailNotAuthenticatedError",
    "EmailProviderConfigError",
    "EmailRecipientsMissingError",
    "EmailRefreshFailedError",
    "EmailReplyContextFetchError",
    "ReplyContext",
    "SyncResult",
    "build_in_reply_to_and_references",
    "build_quoted_body",
    "build_reply_subject",
    "compute_reply_recipients",
    "format_content_disposition",
    "is_blocked_extension",
    "sanitize_filename",
    "validate_reply_threading_coherence",
]
