import { Star } from 'lucide-react';
import { useCallback } from 'react';

type Props = {
  isFavorite: boolean;
  disabled?: boolean;
  onToggle: (next: boolean) => void;
  size?: number;
  ariaLabel?: string;
};

/**
 * Star toggle aligned with Gmail/Outlook conventions: filled = favourite,
 * outlined = not favourite. Click is intercepted so the surrounding row's
 * onClick (open viewer) does not fire when the user only meant to toggle
 * the star.
 */
export default function FavoriteButton({
  isFavorite,
  disabled = false,
  onToggle,
  size = 16,
  ariaLabel,
}: Props) {
  const handleClick = useCallback(
    (event: React.MouseEvent<HTMLButtonElement>) => {
      event.stopPropagation();
      event.preventDefault();
      if (disabled) return;
      onToggle(!isFavorite);
    },
    [disabled, isFavorite, onToggle],
  );

  const handleKeyDown = useCallback((event: React.KeyboardEvent<HTMLButtonElement>) => {
    if (event.key === 'Enter' || event.key === ' ') {
      event.stopPropagation();
    }
  }, []);

  const label = ariaLabel ?? (isFavorite ? 'Quitar de favoritos' : 'Marcar como favorito');

  return (
    <button
      type="button"
      aria-label={label}
      aria-pressed={isFavorite}
      disabled={disabled}
      onClick={handleClick}
      onKeyDown={handleKeyDown}
      className={`grid place-items-center rounded p-0.5 transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-blue-600 ${
        disabled ? 'cursor-not-allowed opacity-50' : 'hover:bg-amber-50'
      }`}
    >
      <Star
        // ``h-[<runtime>]`` cannot be generated by Tailwind's JIT
        // (it scans the source at build time, not runtime), so the
        // size travels via inline ``style`` only — the class string
        // here owns colour and transitions, not sizing.
        className={`transition-colors ${
          isFavorite ? 'fill-amber-400 text-amber-400' : 'text-zinc-400 hover:text-amber-400'
        }`}
        style={{ width: size, height: size }}
        strokeWidth={1.75}
      />
    </button>
  );
}
